name: liber
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_native_splash: ^2.2.0+1
  flutter_launcher_icons: ^0.10.0
  easy_localization: ^3.0.1
  flutter_svg: ^1.0.3
  mask_text_input_formatter: ^2.4.0
  sms_autofill: ^2.2.0
  # hive: ^2.2.3
  # hive_generator: ^1.1.3
  # hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  rating_bar_flutter: ^1.0.2
  audio_manager: ^0.8.2
  audioplayers: ^1.0.1
  flutter_screenutil: ^5.5.4
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.1.0
  image_picker: ^0.8.5+3
  build_runner: ^2.2.0
  infinite_scroll_pagination: ^3.2.0
  shared_preferences: ^2.0.15
  epub_view: ^3.0.0
  internet_file: ^1.2.0
  # vocsy_epub_viewer: ^0.0.8
  permission_handler: ^10.0.1
  pdf_render: ^1.3.4
  url_launcher: ^6.1.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash: 
  color: "#3F51B5"
  image: assets/images/book_icon.png
  image_android: assets/images/book_icon.png
  image_ios: assets/images/book_icon.png
  ios: true
  android: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/Helvetica/
    - assets/fonts/Georgia/
    - assets/fonts/American_Typewriter/
    - assets/fonts/Baskerville/
    - assets/fonts/Times_New_Roman/
    - assets/images/
    - assets/svgs/
    - assets/translations/
  
  fonts:
    #! 300
    - family: Roboto300
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
    #! 400
    - family: Roboto400
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    #! 500
    - family: Roboto500
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    #! Helvetica
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica/Helvetica.ttf
     #! Georgia
    - family: Georgia
      fonts:
        - asset: assets/fonts/Georgia/Georgia.ttf
     #! American_Typewriter
    - family: American_Typewriter
      fonts:
        - asset: assets/fonts/American_Typewriter/American_Typewriter_Regular.ttf
     #! Baskerville
    - family: Baskerville
      fonts:
        - asset: assets/fonts/Baskerville/LibreBaskerville_Regular.ttf
     #! Times_New_Roman
    - family: Times_New_Roman
      fonts:
        - asset: assets/fonts/Times_New_Roman/times_new_roman.ttf
    

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
